### ISSUE TITLE
No need to remove any I2C bytes from the buffer.

### ISSUE THREAD

**Issue by Koepel** [cyclingProfessor/DriverlessCar#1]
In the file "DriverlessCar/camera/Arduino/ReadAsMaster/ReadAsMaster.ino", the garbage bytes are tossed away when the amount of requested bytes was not received. That is not needed.

The Wire library uses packets of data (although it uses the Arduino Stream class).
Every new Wire.requestFrom() and Wire.beginTransmission() starts with an empty buffer.

**Comment by cyclingProfessor** [comment]
Thanks for this - I did not know this!
ReadAsMaster.ino is a test sketch just for seeing if the OpenMV camera hangs so I will not fix this.  In fact it is sometimes useful to see what extra bytes the camera sends and we are ignoring.

**Comment by Koepel** [comment]
Did something change ? I can not find it anymore. I think you used the word "garbage" in that file. Was it in another file, or is there a mix-up of Wire.avaible() and Serial.available() ? I was only talking about the I2C bus and the Wire library.
