### ISSUE TITLE
Store the millis() value as a unsigned long, always use subtraction.

### ISSUE THREAD

**Issue by Koepel** [cyclingProfessor/DriverlessCar#2]
To avoid the rollover problem, the millis() value should be stored as a unsigned long and only a subtraction should be used to calculate the passed time. That subtraction must be done with two unsigned long variables.

See the Blink Without Delay example.

I spotted those problems in the next files. Sometimes the millis() value is stored in a long and sometimes the subtraction is missing. Comparing a value directly with millis() will go wrong with a rollover after about 50 days.

- "DriverlessCar/Sonar/Sonar.ino"
- "DriverlessCar/Polulo/reader/reader.ino"
- "DriverlessCar/lineFollow/Sensor.cpp"
- "DriverlessCar/lineFollow/Actions.cpp"
- "DriverlessCar/lineFollow/lineFollow.ino"
- "DriverlessCar/GyroMagnetAccel/GyroMagnetAccel.ino"

**Comment by cyclingProfessor** [comment]
Thanks for this - however a battery driven toy is unlikely to last 50+ days :-)
Much of the logic for millis() has now changed.
